### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by robinvdvleuten** [laravel-notification-channels/webhook#10]
Now Laravel 5.5 is officially released, it would be nice to have support for it in this package :)

**Comment by kylestev** [comment]
- [x] Add optional composer dependency on `phpunit/phpunit` to 6.0
- [x] Update the `illuminate` dependencies to allow for `5.5.*`
- [x] Update `orchestra/testbench` and `orchestra/database` to [3.5.0](https://github.com/orchestral/database/releases/tag/v3.5.0)
- [x] ~Update `tests/MessageTest` to use reference the new `PHPUnit\Framework\TestCase` class instead of `\PHPUnit_Framework_TestCase`~
  - Possibly just change it to `Orchestra\Testbench\TestCase` to be consistent with `tests/ChannelTest.php`

**Comment by robinvdvleuten** [comment]
Awesome, thanks!
