### ISSUE TITLE
Don't wait for response?

### ISSUE THREAD

**Issue by hipsterjazzbo** [laravel-notification-channels/webhook#2]
Hi there! I love that there's finally an easy way to deal with webhooks in Laravel, but I wonder — is it worth waiting for a response? That could be really slow depending on the destination for the webhook request, and if it is wrong, what can be done about it?

**Comment by mpociot** [comment]
You're right. In the real-world, the webhook notifications should always run through a queue system so you (as the website user) don't have to wait for the response.

You should consider taking a look at my "CaptainHook" package, which provides Webhook logging and retries when using it with a queue system - https://github.com/mpociot/captainhook
And since the webhooks are coupled to events, the usage is also really easy.

**Comment by hipsterjazzbo** [comment]
Well I guess what I'm asking is, why wait for a response at all, queued or not? It might just be the use cases I've had in the past, but I've never seen a case where the response matters. I made [a package](https://github.com/hipsterjazzbo/fire-and-forget) to just open a socket, fire the hook into it and close immediately without waiting for a response.

**Comment by mpociot** [comment]
But if you just "fire and forget" the request, you have no idea if it worked.
In my use-case, the end-user can configure their own webhook endpoints. So they want to know if the webhook worked or not. 

I think if the webhooks can be configured by the user, you should somehow show a response. So it might depend on the specific use-case.
